### ISSUE TITLE
What are the values of the hyperparameters?

### ISSUE THREAD

**Issue by mimi-neoki** [xk-huang/yet-another-vectornet#26]
Hi. I'm interested in VectorNet and appreciate your work.

Could you tell me the values of the hyperparameters to reproduce the result of minADE=2.6 as README say?
I tried to train with the default parameters on this repo following the Usage on README, but the minADE was only about 4-7.

Also I tried with the config.py before the commit 11225a2d58a53a2ec0ff979bb9d12546dcf83325, the result was same.
I didn't forget to run compute_feature_module.py and I tried small_dataset = True and False.
I trained on 8GPUs, but I set batch_size to 4096*2 to reproduce your env.

**Comment by xk-huang** [comment]
Hi @mimi-neoki ! Sorry to reply so late. 
Have you tried the pre-processed data and pre-trained model via the google [drive link](https://drive.google.com/drive/folders/1XJ2Oz4Qc2UstnfRw3DNvQThuEVvM6tUL)? 
I have no idea what happened, but a suggestion is to make sure your python environment followed the `requirement.txt` file.
As to the hyperparameter issue, the checkpoints file I provided is trained under the latest committed codes in the `master` branch.
I also notice that the Argoverse API has changed since last year.
Hope the tips above could help!

**Comment by mimi-neoki** [comment]
Thanks for your reply. 
I tried the preprocessed data and the pre-trained model, and I could confirm that the result was minADE=2.57. My environment is basically the same as in the requirements.txt, including the Argoverse API. However, since the OS is Linux, Windows-specific libraries are not installed such as xlwings. I don't think the presence of these libraries is the cause, but the difference in OS may have affected the training or preprocessing. I will try to test on windows when I get a chance. Whatever the cause, the information that the hyperparameters in the repository are correct is useful to me. Thank you.
